"""
Write Advanced SubStation Alpha (.ass) subtitle files.
Produces Aegisub-compatible output with a sensible default style.
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Sequence
import math


@dataclass
class AssStyle:
    name: str = "Default"
    fontname: str = "Arial"
    fontsize: int = 52
    primary_colour: str = "&H00FFFFFF"   # white, fully opaque
    secondary_colour: str = "&H000000FF"
    outline_colour: str = "&H00000000"   # black outline
    back_colour: str = "&H80000000"      # semi-transparent shadow
    bold: int = -1                       # -1 = bold on
    italic: int = 0
    underline: int = 0
    strike_out: int = 0
    scale_x: int = 100
    scale_y: int = 100
    spacing: int = 0
    angle: float = 0.0
    border_style: int = 1
    outline: float = 2.0
    shadow: float = 2.0
    alignment: int = 2                   # 2 = bottom-center (numpad layout)
    margin_l: int = 10
    margin_r: int = 10
    margin_v: int = 30
    encoding: int = 1


_SCRIPT_INFO = """\
[Script Info]
; Generated by Translation Agent — fansub-quality pipeline
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080
"""

_STYLE_HEADER = (
    "[V4+ Styles]\n"
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
    "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
    "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
    "Alignment, MarginL, MarginR, MarginV, Encoding\n"
)

_EVENTS_HEADER = (
    "\n[Events]\n"
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
)


def _seconds_to_ass_time(seconds: float) -> str:
    """Convert float seconds to ASS timestamp H:MM:SS.cs (centiseconds)."""
    total_cs = int(round(seconds * 100))
    cs = total_cs % 100
    total_s = total_cs // 100
    s = total_s % 60
    total_m = total_s // 60
    m = total_m % 60
    h = total_m // 60
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def _style_line(style: AssStyle) -> str:
    return (
        f"Style: {style.name},{style.fontname},{style.fontsize},"
        f"{style.primary_colour},{style.secondary_colour},"
        f"{style.outline_colour},{style.back_colour},"
        f"{style.bold},{style.italic},{style.underline},{style.strike_out},"
        f"{style.scale_x},{style.scale_y},{style.spacing},{style.angle:.1f},"
        f"{style.border_style},{style.outline:.1f},{style.shadow:.1f},"
        f"{style.alignment},{style.margin_l},{style.margin_r},{style.margin_v},"
        f"{style.encoding}\n"
    )


def write_ass(path: str, cues: Sequence, style: AssStyle | None = None) -> int:
    """
    Write cues to an ASS file. Returns the number of cues written.
    cues must be an iterable of objects with .start (float s), .end (float s), .text (str).
    """
    if style is None:
        style = AssStyle()
    with open(path, "w", encoding="utf-8-sig") as f:
        f.write(_SCRIPT_INFO)
        f.write(_STYLE_HEADER)
        f.write(_style_line(style))
        f.write(_EVENTS_HEADER)
        count = 0
        for cue in cues:
            start = _seconds_to_ass_time(cue.start)
            end = _seconds_to_ass_time(cue.end)
            # Ensure \\N line breaks (postprocess.break_lines already uses \\N)
            text = cue.text.replace("\n", "\\N")
            f.write(
                f"Dialogue: 0,{start},{end},{style.name},,0,0,0,,{text}\n"
            )
            count += 1
    return count